name: ai_dash
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  appwrite: #!As we have done Custom Package Modifications for Appwrite
    path: ./appwrite
  cupertino_icons: ^1.0.2
  lottie: ^2.7.0
  google_fonts: ^6.1.0
  get: ^4.6.6
  hive: ^4.0.0-dev.2        #!for hive database
  isar_flutter_libs: ^4.0.0-dev.13
  path_provider: ^2.1.0     #!for accessing storage path
  flutter_animate: ^4.3.0   #! For Custom Animations
  http: ^1.1.2
  animated_text_kit: ^4.2.2
  dart_openai: ^5.0.0
  cached_network_image: ^3.3.0
  gallery_saver_updated: ^3.0.0
  share_plus: ^7.2.1
  translator_plus: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  #!icons_launcher: ^2.1.6  #for icons launcher

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lottie/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
